{% set name = "elastic-transport" %}
{% set version = "8.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elastic/elastic-transport-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 58dd66a35cf11577e017d2ffb2d85b53523a0f3faa7f89b4b54882987afcdcb4

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - urllib3 >=1.26.2,<3
    - certifi
  run_constrained:
    - httpcore <1.0.6

test:
  imports:
    - elastic_transport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elastic/elastic-transport-python
  summary: Transport classes and utilities shared among Python Elastic client libraries
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Transport classes and utilities shared among Python Elastic client libraries.
  doc_url: https://github.com/elastic/elastic-transport-python
  dev_url: https://github.com/elastic/elastic-transport-python
extra:
  recipe-maintainers:
    - sethmlarson
    - miriam-eid
